SET NAMES 'utf8mb4';
SET CHARACTER SET utf8mb4;

CREATE DATABASE IF NOT EXISTS core
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

-- ==========================================================
-- 1. SEGURIDAD Y USUARIOS (Aislamiento de Core)
-- ==========================================================
-- Crear el usuario específico para el microservicio CORE
CREATE USER IF NOT EXISTS 'user_core'@'%' IDENTIFIED BY 'pass_core_123';

-- Dar permisos solo sobre la base de datos 'core'
GRANT ALL PRIVILEGES ON core.* TO 'user_core'@'%';
FLUSH PRIVILEGES;


USE core;

-- =====================
-- CATÁLOGOS BÁSICOS
-- =====================
CREATE TABLE SKILLS_TYPE (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE SPECIES (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION TEXT NOT NULL
);

CREATE TABLE WEAPONS_TYPE (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE ARMORS_TYPE (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE ITEMS_TYPE (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE RARITY_LEVELS (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL,
  COLOR_HEX VARCHAR(7) NOT NULL,
  DROP_RATE DECIMAL(5,4) NOT NULL
);

CREATE TABLE PRODUCTS_TYPE (
  CODE VARCHAR(4) PRIMARY KEY, -- 'WEAP', 'ARMO', 'ITEM'
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE STORES_TYPE (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE LOCATIONS_TYPE (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE CITIES_TYPE (
  CODE VARCHAR(4) PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL
);

-- Tabla base para todos los objetos
CREATE TABLE PRODUCTS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_TYPE VARCHAR(4) NOT NULL,
  CONSTRAINT fk_prod_type FOREIGN KEY (PRODUCT_TYPE) REFERENCES PRODUCTS_TYPE(CODE)
);

-- =====================
-- SKILLS
-- =====================
CREATE TABLE SKILLS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SKILL_TYPE VARCHAR(4) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  FOREIGN KEY (SKILL_TYPE) REFERENCES SKILLS_TYPE(CODE)
);

CREATE TABLE BASE_STATS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PHYSICAL_ATTACK INT DEFAULT 0,
  MAGIC_ATTACK INT DEFAULT 0,
  EVASION INT DEFAULT 0,
  MANA INT DEFAULT 0,
  VITALITY INT DEFAULT 0,
  PHYSICAL_DEFENSE INT DEFAULT 0,
  MAGIC_DEFENSE INT DEFAULT 0,
  MOVEMENT INT DEFAULT 0
) ENGINE=InnoDB;

-- =====================
-- HEROES
-- =====================
CREATE TABLE HEROES (
  CODE VARCHAR(4) PRIMARY KEY,
  SPECIES_TYPE VARCHAR(4) NOT NULL,
  BASE_STATS_ID BIGINT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  ALIAS VARCHAR(255),
  DESCRIPTION TEXT NOT NULL,
  PORTRAIT_IMAGE_URL VARCHAR(255) NOT NULL,
  CONSTRAINT fk_hero_species FOREIGN KEY (SPECIES_TYPE) REFERENCES SPECIES(CODE),
  CONSTRAINT fk_hero_stats FOREIGN KEY (BASE_STATS_ID) REFERENCES BASE_STATS(ID)
) ENGINE=InnoDB;

CREATE TABLE SKILLS_HEROES (
  SKILL_ID BIGINT NOT NULL,
  HEROE_CODE VARCHAR(4) NOT NULL,
  UNLOCK_LEVEL INT NOT NULL,
  MANA_COST INT NOT NULL,
  PRIMARY KEY (SKILL_ID, HEROE_CODE),
  FOREIGN KEY (SKILL_ID) REFERENCES SKILLS(ID),
  FOREIGN KEY (HEROE_CODE) REFERENCES HEROES(CODE)
);

-- =====================
-- ENEMIES
-- =====================
CREATE TABLE ENEMIES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SPECIES_TYPE VARCHAR(4) NOT NULL,
  BASE_STATS_ID BIGINT NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  IS_BOSS TINYINT(1) NOT NULL,
  REWARD VARCHAR(255),
  PORTRAIT_IMAGE_URL VARCHAR(255) NOT NULL,
  CONSTRAINT fk_enemy_species FOREIGN KEY (SPECIES_TYPE) REFERENCES SPECIES(CODE),
  CONSTRAINT fk_enemy_stats FOREIGN KEY (BASE_STATS_ID) REFERENCES BASE_STATS(ID)
) ENGINE=InnoDB;

CREATE TABLE SKILLS_ENEMIES (
  SKILL_ID BIGINT NOT NULL,
  ENEMY_ID BIGINT NOT NULL,
  USE_LIMIT INT NOT NULL,
  PRIMARY KEY (SKILL_ID, ENEMY_ID),
  FOREIGN KEY (SKILL_ID) REFERENCES SKILLS(ID),
  FOREIGN KEY (ENEMY_ID) REFERENCES ENEMIES(ID)
);

-- =====================
-- EQUIPAMIENTO
-- =====================
CREATE TABLE ARMORS (
  ID BIGINT PRIMARY KEY,
  RARITY VARCHAR(4) NOT NULL,
  ARMOR_TYPE VARCHAR(4) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  PHYSICAL_DEFENSE INT,
  MAGIC_DEFENSE INT,
  UNLOCK_LEVEL INT NOT NULL,
  WEIGHT INT NOT NULL,
  SPECIAL_CONDITION VARCHAR(255),
  FOREIGN KEY (RARITY) REFERENCES RARITY_LEVELS(CODE),
  FOREIGN KEY (ARMOR_TYPE) REFERENCES ARMORS_TYPE(CODE),
  CONSTRAINT fk_armor_product FOREIGN KEY (ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE WEAPONS (
  ID BIGINT PRIMARY KEY,
  RARITY VARCHAR(4) NOT NULL,
  WEAPON_TYPE VARCHAR(4) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  PHYSICAL_ATTACK INT,
  MAGIC_ATTACK INT,
  UNLOCK_LEVEL INT NOT NULL,
  WEIGHT INT NOT NULL,
  SPECIAL_CONDITION VARCHAR(255),
  FOREIGN KEY (RARITY) REFERENCES RARITY_LEVELS(CODE),
  FOREIGN KEY (WEAPON_TYPE) REFERENCES WEAPONS_TYPE(CODE),
  CONSTRAINT fk_weapon_product FOREIGN KEY (ID) REFERENCES PRODUCTS(ID)
);

-- =====================
-- ITEMS
-- =====================
CREATE TABLE ITEMS (
  ID BIGINT PRIMARY KEY,
  ITEM_TYPE VARCHAR(4) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  WEIGHT INT NOT NULL,
  FOREIGN KEY (ITEM_TYPE) REFERENCES ITEMS_TYPE(CODE),
  CONSTRAINT fk_item_product FOREIGN KEY (ID) REFERENCES PRODUCTS(ID)
);

-- =====================
-- WORLD / MAP
-- =====================
CREATE TABLE REGIONS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  MIN_LEVEL INT NOT NULL
);

CREATE TABLE CITIES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REGION_ID BIGINT NOT NULL,
  CITIES_TYPE VARCHAR(4) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  FOREIGN KEY (REGION_ID) REFERENCES REGIONS(ID),
  FOREIGN KEY (CITIES_TYPE) REFERENCES CITIES_TYPE(CODE)
);

CREATE TABLE LOCATIONS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOCATION_TYPE VARCHAR(4) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  FOREIGN KEY (LOCATION_TYPE) REFERENCES LOCATIONS_TYPE(CODE)
);

-- =====================
-- STORES
-- =====================


CREATE TABLE STORES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOCATION_ID BIGINT NOT NULL,
  STORE_TYPE VARCHAR(4) NOT NULL,
  GOLD_LIMIT INT NOT NULL,
  FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID),
  FOREIGN KEY (STORE_TYPE) REFERENCES STORES_TYPE(CODE)
);

CREATE TABLE STORES_INVENTORIES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  STORE_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (STORE_ID) REFERENCES STORES(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

